# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
   
  config.vm.define "manager" do |manager|
  
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.synced_folder "services", "/home/services"
    manager.vm.synced_folder "scripts", "/home/scripts"
    manager.vm.provision "shell", path: "scripts/swap.sh"
    manager.vm.network "forwarded_port", guest: 9090, host: 9090
    manager.vm.network "forwarded_port", guest: 3000, host: 3000
    end
    
  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.provision "shell", path: "scripts/swap.sh"
    node.vm.network "forwarded_port", guest: 5432,  host: 15432,  auto_correct: true
    node.vm.network "forwarded_port", guest: 5672,  host: 15672,  auto_correct: true
    node.vm.network "forwarded_port", guest: 15672, host: 25672,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8081,  host: 8081,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8082,  host: 8082,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8083,  host: 8083,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8084,  host: 8084,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8085,  host: 8085,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8086,  host: 8086,  auto_correct: true
    node.vm.network "forwarded_port", guest: 8087,  host: 8087,  auto_correct: true

    end
    
  config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.network "private_network", ip: "192.168.56.12"
    node.vm.network "forwarded_port", guest: 80,  host: 80,  auto_correct: true
    node.vm.provision "shell", path: "scripts/swap.sh"
    end
end
